on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Updates Blog Outline
      uses: WeiYun0912/js-action@v2.15
      with:
        COMMITTER_USERNAME : "WeiYun0912"
        COMMITTER_EMAIL : "yher25@gmail.com"
        MAX_LINES: '8'