on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: WeiYun0912/js-action@v2.10
      with:
        sitemap: 'https://weiyun0912.github.io/Wei-Docusaurus/sitemap.xml'